name: This is a github action
on: [push]
jobs: 
  Echo: #name of job which runs on ubuntu
    runs-on: ubuntu-latest 
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: cat temp.txt
        run: cat temp.txt
